In [1]:
import numpy as np

Q = np.array([
    [0.13,0.45],
    [0.11,0.69],
    [0.13,0.45],
    [0.12,0.61]])

K = np.array([
    [0.14,0.46],
    [0.10,0.72],
    [0.14,0.46],
    [0.12,0.64]])

V = np.array([
    [0.05,0.6],
    [0.02,0.96],
    [0.05,0.60],
    [0.03,0.84]])

In [10]:
def softmax(x):
    z = x
    numerator = np.exp(z)
    denominator = np.sum(numerator, axis=-1, keepdims=True)
    return numerator / denominator

In [15]:
mult_1 = softmax(Q @ K.T)
print(mult_1)

[[0.23810406 0.26626919 0.23810406 0.25752268]
 [0.23142789 0.2756876  0.23142789 0.26145661]
 [0.23810406 0.26626919 0.23810406 0.25752268]
 [0.23366467 0.2725132  0.23366467 0.26015746]]


In [17]:
mult_1[0].sum()

np.float64(1.0)

In [18]:
mult_1 @ V

array([[0.03686147, 0.75766235],
       [0.03650024, 0.76199712],
       [0.03686147, 0.75766235],
       [0.03662145, 0.76054254]])